import {
  UserProfile,
  GlucoseReading,
  Medication,
  MedicationLog,
  Meal,
  Activity,
  Appointment,
  TodayPlanItem,
  RationItem,
  UserPermissions,
  LabReport,
} from "@/types";

export const DEFAULT_PATIENT_PERMISSIONS: UserPermissions = {
  canLogGlucose: true,
  canManageMedications: true,
  canLogMeals: true,
  canManageRation: true,
  canLogActivity: true,
  canManageAppointments: true,
  canViewReports: true,
  canExportData: true,
};

export const DEFAULT_DOCTOR_PERMISSIONS: UserPermissions = {
  canLogGlucose: true,
  canManageMedications: true,
  canLogMeals: true,
  canManageRation: false,
  canLogActivity: true,
  canManageAppointments: true,
  canViewReports: true,
  canExportData: true,
};

export const DEFAULT_ADMIN_PERMISSIONS: UserPermissions = {
  canLogGlucose: true,
  canManageMedications: true,
  canLogMeals: true,
  canManageRation: true,
  canLogActivity: true,
  canManageAppointments: true,
  canViewReports: true,
  canExportData: true,
};

export const DEMO_USER_ID = "demo-patient-001";
export const DEMO_ADMIN_ID = "demo-admin-001";
export const DEMO_DOCTOR_ID = "demo-doctor-001";

export const demoUser: UserProfile = {
  id: DEMO_USER_ID,
  name: "Eleanor Brooks",
  email: "eleanor.brooks@example.com",
  role: "patient",
  status: "active",
  permissions: { ...DEFAULT_PATIENT_PERMISSIONS },
  diabetesType: "Type 2",
  glucoseUnit: "mg/dL",
  targetRange: {
    fastingMin: 70,
    fastingMax: 130,
    postMealMax: 180,
  },
  notifications: {
    medicationReminders: true,
    glucoseReminders: true,
    appointmentReminders: true,
  },
  createdAt: "2024-01-15T08:00:00.000Z",
};

export const demoAdminUser: UserProfile = {
  id: DEMO_ADMIN_ID,
  name: "Dr. Marcus Vance (Admin)",
  email: "admin@glucocare.health",
  role: "admin",
  status: "active",
  permissions: { ...DEFAULT_ADMIN_PERMISSIONS },
  diabetesType: "Type 2",
  glucoseUnit: "mg/dL",
  targetRange: {
    fastingMin: 70,
    fastingMax: 130,
    postMealMax: 180,
  },
  notifications: {
    medicationReminders: true,
    glucoseReminders: true,
    appointmentReminders: true,
  },
  createdAt: "2023-11-01T09:00:00.000Z",
};

export const demoDoctorUser: UserProfile = {
  id: DEMO_DOCTOR_ID,
  name: "Dr. Sarah Chen, MD",
  email: "sarah.chen@glucocare.health",
  role: "doctor",
  status: "active",
  permissions: { ...DEFAULT_DOCTOR_PERMISSIONS },
  diabetesType: "Other",
  glucoseUnit: "mg/dL",
  targetRange: {
    fastingMin: 70,
    fastingMax: 130,
    postMealMax: 180,
  },
  notifications: {
    medicationReminders: false,
    glucoseReminders: false,
    appointmentReminders: true,
  },
  createdAt: "2024-02-10T10:00:00.000Z",
};

export const demoSeedUsers: UserProfile[] = [
  demoUser,
  demoAdminUser,
  demoDoctorUser,
  {
    id: "demo-patient-002",
    name: "Arthur Pendelton",
    email: "arthur.pendelton@example.com",
    role: "patient",
    status: "active",
    permissions: {
      ...DEFAULT_PATIENT_PERMISSIONS,
      canManageRation: false, // Ration restricted by admin
    },
    diabetesType: "Type 2",
    glucoseUnit: "mg/dL",
    targetRange: { fastingMin: 80, fastingMax: 140, postMealMax: 190 },
    notifications: { medicationReminders: true, glucoseReminders: true, appointmentReminders: false },
    createdAt: "2024-03-01T11:20:00.000Z",
  },
  {
    id: "demo-patient-003",
    name: "Chloe Martinez",
    email: "chloe.martinez@example.com",
    role: "patient",
    status: "active",
    permissions: { ...DEFAULT_PATIENT_PERMISSIONS },
    diabetesType: "Type 1",
    glucoseUnit: "mg/dL",
    targetRange: { fastingMin: 70, fastingMax: 120, postMealMax: 160 },
    notifications: { medicationReminders: true, glucoseReminders: true, appointmentReminders: true },
    createdAt: "2024-03-12T14:45:00.000Z",
  },
  {
    id: "demo-patient-004",
    name: "Robert Taylor",
    email: "robert.taylor@example.com",
    role: "patient",
    status: "suspended",
    permissions: { ...DEFAULT_PATIENT_PERMISSIONS, canLogGlucose: false },
    diabetesType: "Prediabetes",
    glucoseUnit: "mg/dL",
    targetRange: { fastingMin: 70, fastingMax: 110, postMealMax: 140 },
    notifications: { medicationReminders: false, glucoseReminders: false, appointmentReminders: false },
    createdAt: "2024-02-18T08:15:00.000Z",
  },
];


// Generate date strings relative to today for a live feel
function getRelativeDateStr(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split("T")[0];
}

const today = getRelativeDateStr(0);
const yesterday = getRelativeDateStr(1);
const twoDaysAgo = getRelativeDateStr(2);
const threeDaysAgo = getRelativeDateStr(3);
const fourDaysAgo = getRelativeDateStr(4);
const fiveDaysAgo = getRelativeDateStr(5);
const sixDaysAgo = getRelativeDateStr(6);
const sevenDaysAgo = getRelativeDateStr(7);

export const demoMedications: Medication[] = [
  {
    id: "med-1",
    userId: DEMO_USER_ID,
    name: "Metformin",
    dosage: "500 mg",
    frequency: "Twice daily",
    instructions: "Take with meals (breakfast and dinner) to minimize stomach upset",
    schedule: "morning",
    startDate: "2023-05-10",
    active: true,
    createdAt: "2023-05-10T09:00:00.000Z",
    updatedAt: "2023-05-10T09:00:00.000Z",
  },
  {
    id: "med-2",
    userId: DEMO_USER_ID,
    name: "Glipizide",
    dosage: "5 mg",
    frequency: "Once daily",
    instructions: "Take 30 minutes before first meal of the day",
    schedule: "morning",
    startDate: "2023-08-20",
    active: true,
    createdAt: "2023-08-20T10:00:00.000Z",
    updatedAt: "2023-08-20T10:00:00.000Z",
  },
  {
    id: "med-3",
    userId: DEMO_USER_ID,
    name: "Atorvastatin",
    dosage: "20 mg",
    frequency: "Once daily",
    instructions: "Take at bedtime with water",
    schedule: "bedtime",
    startDate: "2023-05-10",
    active: true,
    createdAt: "2023-05-10T09:30:00.000Z",
    updatedAt: "2023-05-10T09:30:00.000Z",
  },
];

export const demoMedicationLogs: MedicationLog[] = [
  {
    id: "mlog-1",
    userId: DEMO_USER_ID,
    medicationId: "med-1",
    medicationName: "Metformin (500 mg)",
    dosage: "500 mg",
    scheduledAt: `${today}T08:00:00.000Z`,
    takenAt: `${today}T08:14:00.000Z`,
    status: "taken",
    notes: "Taken with breakfast",
    createdAt: `${today}T08:15:00.000Z`,
  },
  {
    id: "mlog-2",
    userId: DEMO_USER_ID,
    medicationId: "med-2",
    medicationName: "Glipizide (5 mg)",
    dosage: "5 mg",
    scheduledAt: `${today}T07:30:00.000Z`,
    takenAt: `${today}T07:32:00.000Z`,
    status: "taken",
    notes: "Taken 30 min prior to eating",
    createdAt: `${today}T07:35:00.000Z`,
  },
];

export const demoGlucoseReadings: GlucoseReading[] = [
  // Today's readings
  {
    id: "glu-today-2",
    userId: DEMO_USER_ID,
    value: 118,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${today}T13:42:00.000Z`,
    date: today,
    time: "13:42",
    notes: "2 hrs after chicken salad lunch",
    createdAt: `${today}T13:43:00.000Z`,
    updatedAt: `${today}T13:43:00.000Z`,
  },
  {
    id: "glu-today-1",
    userId: DEMO_USER_ID,
    value: 104,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${today}T07:15:00.000Z`,
    date: today,
    time: "07:15",
    notes: "Woke up feeling well rested",
    createdAt: `${today}T07:16:00.000Z`,
    updatedAt: `${today}T07:16:00.000Z`,
  },
  // Yesterday
  {
    id: "glu-yest-3",
    userId: DEMO_USER_ID,
    value: 122,
    unit: "mg/dL",
    context: "bedtime",
    measuredAt: `${yesterday}T22:10:00.000Z`,
    date: yesterday,
    time: "22:10",
    notes: "Before sleep",
    createdAt: `${yesterday}T22:10:00.000Z`,
    updatedAt: `${yesterday}T22:10:00.000Z`,
  },
  {
    id: "glu-yest-2",
    userId: DEMO_USER_ID,
    value: 142,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${yesterday}T14:05:00.000Z`,
    date: yesterday,
    time: "14:05",
    notes: "Post lunch",
    createdAt: `${yesterday}T14:05:00.000Z`,
    updatedAt: `${yesterday}T14:05:00.000Z`,
  },
  {
    id: "glu-yest-1",
    userId: DEMO_USER_ID,
    value: 109,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${yesterday}T07:20:00.000Z`,
    date: yesterday,
    time: "07:20",
    notes: "Morning fasting check",
    createdAt: `${yesterday}T07:20:00.000Z`,
    updatedAt: `${yesterday}T07:20:00.000Z`,
  },
  // Two days ago
  {
    id: "glu-2d-3",
    userId: DEMO_USER_ID,
    value: 135,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${twoDaysAgo}T20:15:00.000Z`,
    date: twoDaysAgo,
    time: "20:15",
    notes: "After dinner salmon & greens",
    createdAt: `${twoDaysAgo}T20:15:00.000Z`,
    updatedAt: `${twoDaysAgo}T20:15:00.000Z`,
  },
  {
    id: "glu-2d-2",
    userId: DEMO_USER_ID,
    value: 128,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${twoDaysAgo}T13:30:00.000Z`,
    date: twoDaysAgo,
    time: "13:30",
    notes: "Post lunch check",
    createdAt: `${twoDaysAgo}T13:30:00.000Z`,
    updatedAt: `${twoDaysAgo}T13:30:00.000Z`,
  },
  {
    id: "glu-2d-1",
    userId: DEMO_USER_ID,
    value: 112,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${twoDaysAgo}T07:05:00.000Z`,
    date: twoDaysAgo,
    time: "07:05",
    notes: "Morning fasting",
    createdAt: `${twoDaysAgo}T07:05:00.000Z`,
    updatedAt: `${twoDaysAgo}T07:05:00.000Z`,
  },
  // Three days ago
  {
    id: "glu-3d-2",
    userId: DEMO_USER_ID,
    value: 154,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${threeDaysAgo}T14:15:00.000Z`,
    date: threeDaysAgo,
    time: "14:15",
    notes: "Slightly higher after whole grain pasta",
    createdAt: `${threeDaysAgo}T14:15:00.000Z`,
    updatedAt: `${threeDaysAgo}T14:15:00.000Z`,
  },
  {
    id: "glu-3d-1",
    userId: DEMO_USER_ID,
    value: 98,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${threeDaysAgo}T07:10:00.000Z`,
    date: threeDaysAgo,
    time: "07:10",
    notes: "Morning fasting",
    createdAt: `${threeDaysAgo}T07:10:00.000Z`,
    updatedAt: `${threeDaysAgo}T07:10:00.000Z`,
  },
  // Four days ago
  {
    id: "glu-4d-2",
    userId: DEMO_USER_ID,
    value: 130,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${fourDaysAgo}T19:45:00.000Z`,
    date: fourDaysAgo,
    time: "19:45",
    notes: "After light dinner",
    createdAt: `${fourDaysAgo}T19:45:00.000Z`,
    updatedAt: `${fourDaysAgo}T19:45:00.000Z`,
  },
  {
    id: "glu-4d-1",
    userId: DEMO_USER_ID,
    value: 106,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${fourDaysAgo}T07:30:00.000Z`,
    date: fourDaysAgo,
    time: "07:30",
    notes: "Morning fasting",
    createdAt: `${fourDaysAgo}T07:30:00.000Z`,
    updatedAt: `${fourDaysAgo}T07:30:00.000Z`,
  },
  // Five days ago
  {
    id: "glu-5d-2",
    userId: DEMO_USER_ID,
    value: 148,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${fiveDaysAgo}T13:50:00.000Z`,
    date: fiveDaysAgo,
    time: "13:50",
    notes: "Post lunch",
    createdAt: `${fiveDaysAgo}T13:50:00.000Z`,
    updatedAt: `${fiveDaysAgo}T13:50:00.000Z`,
  },
  {
    id: "glu-5d-1",
    userId: DEMO_USER_ID,
    value: 115,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${fiveDaysAgo}T07:25:00.000Z`,
    date: fiveDaysAgo,
    time: "07:25",
    notes: "Morning fasting",
    createdAt: `${fiveDaysAgo}T07:25:00.000Z`,
    updatedAt: `${fiveDaysAgo}T07:25:00.000Z`,
  },
  // Six days ago
  {
    id: "glu-6d-2",
    userId: DEMO_USER_ID,
    value: 139,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${sixDaysAgo}T19:30:00.000Z`,
    date: sixDaysAgo,
    time: "19:30",
    notes: "Dinner reading",
    createdAt: `${sixDaysAgo}T19:30:00.000Z`,
    updatedAt: `${sixDaysAgo}T19:30:00.000Z`,
  },
  {
    id: "glu-6d-1",
    userId: DEMO_USER_ID,
    value: 101,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${sixDaysAgo}T07:15:00.000Z`,
    date: sixDaysAgo,
    time: "07:15",
    notes: "Morning fasting",
    createdAt: `${sixDaysAgo}T07:15:00.000Z`,
    updatedAt: `${sixDaysAgo}T07:15:00.000Z`,
  },
  // Seven days ago
  {
    id: "glu-7d-2",
    userId: DEMO_USER_ID,
    value: 134,
    unit: "mg/dL",
    context: "after_meal",
    measuredAt: `${sevenDaysAgo}T13:40:00.000Z`,
    date: sevenDaysAgo,
    time: "13:40",
    notes: "Post lunch check",
    createdAt: `${sevenDaysAgo}T13:40:00.000Z`,
    updatedAt: `${sevenDaysAgo}T13:40:00.000Z`,
  },
  {
    id: "glu-7d-1",
    userId: DEMO_USER_ID,
    value: 108,
    unit: "mg/dL",
    context: "fasting",
    measuredAt: `${sevenDaysAgo}T07:40:00.000Z`,
    date: sevenDaysAgo,
    time: "07:40",
    notes: "Morning fasting",
    createdAt: `${sevenDaysAgo}T07:40:00.000Z`,
    updatedAt: `${sevenDaysAgo}T07:40:00.000Z`,
  },
];

const currentMonth = today.slice(0, 7);

export const demoRationItems: RationItem[] = [
  {
    id: "rat-1",
    userId: DEMO_USER_ID,
    name: "Steel-cut Oats",
    category: "grains",
    allocatedQuantity: 2000,
    usedQuantity: 650,
    unit: "g",
    month: currentMonth,
    lowStockThreshold: 400,
    notes: "Organic high-fiber oats for breakfast",
    createdAt: `${currentMonth}-01T08:00:00.000Z`,
    updatedAt: `${today}T08:25:00.000Z`,
  },
  {
    id: "rat-2",
    userId: DEMO_USER_ID,
    name: "Brown Basmati Rice",
    category: "grains",
    allocatedQuantity: 3000,
    usedQuantity: 1200,
    unit: "g",
    month: currentMonth,
    lowStockThreshold: 500,
    notes: "Low glycemic index whole grain rice",
    createdAt: `${currentMonth}-01T08:00:00.000Z`,
    updatedAt: `${today}T12:55:00.000Z`,
  },
  {
    id: "rat-3",
    userId: DEMO_USER_ID,
    name: "Yellow Moong Dal (Lentils)",
    category: "pulses",
    allocatedQuantity: 2500,
    usedQuantity: 1000,
    unit: "g",
    month: currentMonth,
    lowStockThreshold: 500,
    notes: "Easy-to-digest diabetic plant protein",
    createdAt: `${currentMonth}-01T08:00:00.000Z`,
    updatedAt: `${today}T12:55:00.000Z`,
  },
  {
    id: "rat-4",
    userId: DEMO_USER_ID,
    name: "Chia Seeds",
    category: "nuts_seeds",
    allocatedQuantity: 500,
    usedQuantity: 420,
    unit: "g",
    month: currentMonth,
    lowStockThreshold: 100,
    notes: "Omega-3 and soluble fiber for glucose stability",
    createdAt: `${currentMonth}-01T08:00:00.000Z`,
    updatedAt: `${today}T08:25:00.000Z`,
  },
  {
    id: "rat-5",
    userId: DEMO_USER_ID,
    name: "Raw Almonds & Walnuts",
    category: "nuts_seeds",
    allocatedQuantity: 1000,
    usedQuantity: 450,
    unit: "g",
    month: currentMonth,
    lowStockThreshold: 200,
    notes: "Healthy fats to prevent blood sugar spikes",
    createdAt: `${currentMonth}-01T08:00:00.000Z`,
    updatedAt: `${today}T16:10:00.000Z`,
  },
  {
    id: "rat-6",
    userId: DEMO_USER_ID,
    name: "Extra Virgin Olive Oil",
    category: "oils",
    allocatedQuantity: 1000,
    usedQuantity: 400,
    unit: "ml",
    month: currentMonth,
    lowStockThreshold: 200,
    notes: "Cold pressed for cooking and dressings",
    createdAt: `${currentMonth}-01T08:00:00.000Z`,
    updatedAt: `${today}T12:55:00.000Z`,
  },
];

export const demoMeals: Meal[] = [
  {
    id: "meal-1",
    userId: DEMO_USER_ID,
    mealType: "breakfast",
    description: "Steel-cut oatmeal with blueberries, cinnamon & chia seeds",
    time: "08:00",
    date: today,
    calories: 340,
    carbohydrates: 42,
    protein: 10,
    notes: "Very satisfying, low glycemic load",
    rationIngredients: [
      { rationId: "rat-1", rationName: "Steel-cut Oats", quantity: 50, unit: "g" },
      { rationId: "rat-4", rationName: "Chia Seeds", quantity: 15, unit: "g" },
    ],
    createdAt: `${today}T08:25:00.000Z`,
  },
  {
    id: "meal-2",
    userId: DEMO_USER_ID,
    mealType: "lunch",
    description: "Mediterranean grilled chicken salad with avocado & olive oil",
    time: "12:30",
    date: today,
    calories: 450,
    carbohydrates: 14,
    protein: 38,
    notes: "Drank sparkling water with lemon",
    rationIngredients: [
      { rationId: "rat-6", rationName: "Extra Virgin Olive Oil", quantity: 15, unit: "ml" },
    ],
    createdAt: `${today}T12:55:00.000Z`,
  },
  {
    id: "meal-3",
    userId: DEMO_USER_ID,
    mealType: "snack",
    description: "A small handful of roasted almonds & cucumber slices",
    time: "16:00",
    date: today,
    calories: 160,
    carbohydrates: 6,
    protein: 6,
    notes: "Quick afternoon snack",
    rationIngredients: [
      { rationId: "rat-5", rationName: "Raw Almonds & Walnuts", quantity: 25, unit: "g" },
    ],
    createdAt: `${today}T16:10:00.000Z`,
  },
  {
    id: "meal-4",
    userId: DEMO_USER_ID,
    mealType: "dinner",
    description: "Baked wild salmon, steamed broccoli, and quinoa",
    time: "19:00",
    date: yesterday,
    calories: 520,
    carbohydrates: 28,
    protein: 44,
    notes: "Felt very good after dinner",
    createdAt: `${yesterday}T19:40:00.000Z`,
  },
];

export const demoActivities: Activity[] = [
  {
    id: "act-1",
    userId: DEMO_USER_ID,
    activityType: "walking",
    durationMinutes: 35,
    date: today,
    time: "08:45",
    steps: 3820,
    notes: "Pleasant morning neighborhood walk after breakfast",
    createdAt: `${today}T09:25:00.000Z`,
  },
  {
    id: "act-2",
    userId: DEMO_USER_ID,
    activityType: "walking",
    durationMinutes: 25,
    date: yesterday,
    time: "17:30",
    steps: 2750,
    notes: "Evening walk around the park",
    createdAt: `${yesterday}T18:00:00.000Z`,
  },
  {
    id: "act-3",
    userId: DEMO_USER_ID,
    activityType: "cycling",
    durationMinutes: 40,
    date: twoDaysAgo,
    time: "10:00",
    steps: undefined,
    notes: "Stationary bike gentle cardio",
    createdAt: `${twoDaysAgo}T10:45:00.000Z`,
  },
  {
    id: "act-4",
    userId: DEMO_USER_ID,
    activityType: "yoga",
    durationMinutes: 30,
    date: threeDaysAgo,
    time: "07:30",
    steps: 600,
    notes: "Morning gentle stretching and balance",
    createdAt: `${threeDaysAgo}T08:05:00.000Z`,
  },
  {
    id: "act-5",
    userId: DEMO_USER_ID,
    activityType: "walking",
    durationMinutes: 45,
    date: fourDaysAgo,
    time: "09:00",
    steps: 4900,
    notes: "Long weekend walk with family",
    createdAt: `${fourDaysAgo}T09:50:00.000Z`,
  },
  {
    id: "act-6",
    userId: DEMO_USER_ID,
    activityType: "walking",
    durationMinutes: 30,
    date: fiveDaysAgo,
    time: "18:15",
    steps: 3200,
    notes: "Post-dinner neighborhood walk",
    createdAt: `${fiveDaysAgo}T18:50:00.000Z`,
  },
];

export const demoAppointments: Appointment[] = [
  {
    id: "app-1",
    userId: DEMO_USER_ID,
    title: "Quarterly Diabetes Check & HbA1c Review",
    doctorName: "Dr. Sarah Jenkins, MD",
    specialty: "Endocrinology",
    date: getRelativeDateStr(-4), // 4 days in the future
    time: "10:30",
    location: "Riverside Endocrine Health, Suite 410",
    isVirtual: false,
    reminderAlarm: "1h",
    notes: "Review 90-day glucose trends, HbA1c results, and routine kidney function panel.",
    completed: false,
    createdAt: "2024-02-01T10:00:00.000Z",
  },
  {
    id: "app-2",
    userId: DEMO_USER_ID,
    title: "Annual Diabetic Retinal Eye Exam",
    doctorName: "Dr. Robert Vance, OD",
    specialty: "Ophthalmology",
    date: getRelativeDateStr(-21), // 3 weeks in the future
    time: "14:15",
    location: "Vision Specialists Center",
    isVirtual: false,
    reminderAlarm: "2h",
    notes: "Pupil dilation planned. Bring sunglasses and arranged ride home.",
    completed: false,
    createdAt: "2024-02-05T11:00:00.000Z",
  },
  {
    id: "app-3",
    userId: DEMO_USER_ID,
    title: "Dietitian Nutrition Consultation",
    doctorName: "Karen Lee, MS, RD, CDCES",
    specialty: "Certified Diabetes Care & Education",
    date: getRelativeDateStr(12), // 12 days ago
    time: "11:00",
    location: "Telehealth Video Call",
    isVirtual: true,
    reminderAlarm: "15m",
    notes: "Discussed healthy complex carbohydrate substitutions and meal timing.",
    completed: true,
    createdAt: "2024-01-20T14:00:00.000Z",
  },
];

export const demoTodayPlan: TodayPlanItem[] = [
  {
    id: "plan-1",
    title: "Morning Medication",
    subtitle: "Metformin 500 mg & Glipizide 5 mg",
    time: "8:00 AM",
    category: "medication",
    completed: true,
  },
  {
    id: "plan-2",
    title: "Breakfast Log",
    subtitle: "Steel-cut oatmeal logged",
    time: "8:30 AM",
    category: "meal",
    completed: true,
  },
  {
    id: "plan-3",
    title: "Post-Lunch Glucose Check",
    subtitle: "Recorded: 118 mg/dL",
    time: "1:40 PM",
    category: "glucose",
    completed: true,
  },
  {
    id: "plan-4",
    title: "Evening Medication",
    subtitle: "Metformin 500 mg with dinner",
    time: "7:00 PM",
    category: "medication",
    completed: false,
  },
  {
    id: "plan-5",
    title: "Evening Walk / Gentle Cardio",
    subtitle: "Aim for 20-30 minutes active time",
    time: "7:45 PM",
    category: "activity",
    completed: false,
  },
  {
    id: "plan-6",
    title: "Bedtime Medication & Check",
    subtitle: "Atorvastatin 20 mg",
    time: "10:00 PM",
    category: "medication",
    completed: false,
  },
];

export const demoLabReports: LabReport[] = [
  {
    id: "rep-1",
    userId: DEMO_USER_ID,
    title: "Quarterly Comprehensive Metabolic & Glycated Hemoglobin (HbA1c) Panel",
    doctorOrLab: "Metropolis Healthcare / Quest Diagnostics",
    category: "hba1c",
    date: getRelativeDateStr(14),
    summaryMetrics: "HbA1c: 6.8% (Target < 7.0%), eAG: 148 mg/dL, Fasting Glucose: 112 mg/dL",
    notes: "Significant positive trend compared to last quarter (was 7.4%). Microalbumin/Creatinine ratio normal.",
    fileName: "Metropolis_HbA1c_CMP_Report.pdf",
    fileSize: "1.4 MB",
    fileType: "application/pdf",
    createdAt: new Date().toISOString(),
  },
  {
    id: "rep-2",
    userId: DEMO_USER_ID,
    title: "Lipid Profile & Cardiovascular Risk Evaluation",
    doctorOrLab: "Thyrocare Technologies",
    category: "lipid_panel",
    date: getRelativeDateStr(35),
    summaryMetrics: "Total Chol: 168 mg/dL, HDL: 48 mg/dL, LDL: 94 mg/dL, Triglycerides: 138 mg/dL",
    notes: "Lipid fractions improved under active lifestyle and olive oil cooking routine.",
    fileName: "Thyrocare_Lipid_Panel_Certified.pdf",
    fileSize: "840 KB",
    fileType: "application/pdf",
    createdAt: new Date().toISOString(),
  },
  {
    id: "rep-3",
    userId: DEMO_USER_ID,
    title: "Clinical Follow-up & Medication Prescription Slip",
    doctorOrLab: "Dr. Sarah Jenkins, MD (Endocrinology)",
    category: "prescription",
    date: getRelativeDateStr(45),
    summaryMetrics: "Metformin 500mg BID, Glipizide 5mg QD",
    notes: "Maintain regular 30-min walking after dinner. Repeat HbA1c in 3 months.",
    fileName: "DrJenkins_Rx_CarePlan.pdf",
    fileSize: "520 KB",
    fileType: "application/pdf",
    createdAt: new Date().toISOString(),
  },
];


